<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ServiceCatalog\Entities\" />
    <Folder Include="ServiceCatalog\DomainServices\" />
    <Folder Include="ServiceCatalog\Events\" />
  </ItemGroup>

</Project>
