// <auto-generated />
using System;
using HelpDesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.Infrastructure.Attachments.Models.AttachmentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PublicUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UploadedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Collaboration.Models.CommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComments", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.IdentityAccess.Models.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.johnson@acme.com",
                            Name = "Alice Johnson",
                            Role = "Requester"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob.miller@acme.com",
                            Name = "Bob Miller",
                            Role = "Agent"
                        },
                        new
                        {
                            Id = 3,
                            Email = "clara.thompson@acme.com",
                            Name = "Clara Thompson",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 4,
                            Email = "david.anderson@acme.com",
                            Name = "David Anderson",
                            Role = "Requester"
                        },
                        new
                        {
                            Id = 5,
                            Email = "emily.carter@acme.com",
                            Name = "Emily Carter",
                            Role = "Agent"
                        },
                        new
                        {
                            Id = 6,
                            Email = "frank.harris@acme.com",
                            Name = "Frank Harris",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 7,
                            Email = "grace.lewis@acme.com",
                            Name = "Grace Lewis",
                            Role = "Requester"
                        },
                        new
                        {
                            Id = 8,
                            Email = "henry.clark@acme.com",
                            Name = "Henry Clark",
                            Role = "Agent"
                        },
                        new
                        {
                            Id = 9,
                            Email = "isabella.scott@acme.com",
                            Name = "Isabella Scott",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 10,
                            Email = "jack.wilson@acme.com",
                            Name = "Jack Wilson",
                            Role = "Requester"
                        });
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.ServiceCatalog.Models.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Infraestrutura"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aplicações"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Redes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Segurança"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Suporte"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Serviços em Nuvem",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bancos de Dados",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Firewall",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Central de Ajuda",
                            ParentId = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "LAN/WAN",
                            ParentId = 3
                        });
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Ticketing.Models.TicketActionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("varchar(600)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketActions", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Ticketing.Models.TicketEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PriorityLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("RequesterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SlaDueAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SlaStartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Attachments.Models.AttachmentEntity", b =>
                {
                    b.HasOne("HelpDesk.Infrastructure.Ticketing.Models.TicketEntity", null)
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.Infrastructure.IdentityAccess.Models.UserEntity", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Collaboration.Models.CommentEntity", b =>
                {
                    b.HasOne("HelpDesk.Infrastructure.IdentityAccess.Models.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HelpDesk.Infrastructure.Ticketing.Models.TicketEntity", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.ServiceCatalog.Models.CategoryEntity", b =>
                {
                    b.HasOne("HelpDesk.Infrastructure.ServiceCatalog.Models.CategoryEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Ticketing.Models.TicketActionEntity", b =>
                {
                    b.HasOne("HelpDesk.Infrastructure.Ticketing.Models.TicketEntity", "Ticket")
                        .WithMany("Actions")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Ticketing.Models.TicketEntity", b =>
                {
                    b.HasOne("HelpDesk.Infrastructure.IdentityAccess.Models.UserEntity", "Assignee")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HelpDesk.Infrastructure.ServiceCatalog.Models.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HelpDesk.Infrastructure.IdentityAccess.Models.UserEntity", "Requester")
                        .WithMany("RequestedTickets")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignee");

                    b.Navigation("Category");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.IdentityAccess.Models.UserEntity", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("RequestedTickets");
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.ServiceCatalog.Models.CategoryEntity", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Ticketing.Models.TicketEntity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Attachments");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
